"""Drop new conversation tables

Revision ID: 542695f1b434
Revises: 237e50cbba07
Create Date: 2025-02-19 16:27:55.912871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '542695f1b434'
down_revision: Union[str, None] = '237e50cbba07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign keys from external_references
    op.drop_constraint(None, 'external_references', type_='foreignkey')
    op.drop_constraint(None, 'external_references', type_='foreignkey')
    op.drop_index('ix_external_references_property_conversation_id', table_name='external_references')
    op.drop_index('ix_external_references_general_conversation_id', table_name='external_references')
    
    # Drop property_messages table and its indexes
    op.drop_index('ix_property_messages_timestamp', table_name='property_messages')
    op.drop_index('ix_property_messages_id', table_name='property_messages')
    op.drop_index('ix_property_messages_conversation_id', table_name='property_messages')
    op.drop_table('property_messages')
    
    # Drop general_messages table and its indexes
    op.drop_index('ix_general_messages_timestamp', table_name='general_messages')
    op.drop_index('ix_general_messages_id', table_name='general_messages')
    op.drop_index('ix_general_messages_conversation_id', table_name='general_messages')
    op.drop_table('general_messages')
    
    # Drop property_conversations table and its indexes
    op.drop_index('ix_property_conversations_user_id', table_name='property_conversations')
    op.drop_index('ix_property_conversations_session_id', table_name='property_conversations')
    op.drop_index('ix_property_conversations_seller_id', table_name='property_conversations')
    op.drop_index('ix_property_conversations_property_id', table_name='property_conversations')
    op.drop_index('ix_property_conversations_id', table_name='property_conversations')
    op.drop_table('property_conversations')
    
    # Drop general_conversations table and its indexes
    op.drop_index('ix_general_conversations_user_id', table_name='general_conversations')
    op.drop_index('ix_general_conversations_session_id', table_name='general_conversations')
    op.drop_index('ix_general_conversations_id', table_name='general_conversations')
    op.drop_table('general_conversations')
    
    # Drop new columns from external_references
    op.drop_column('external_references', 'property_conversation_id')
    op.drop_column('external_references', 'general_conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to external_references
    op.add_column('external_references', sa.Column('general_conversation_id', sa.Integer(), nullable=True))
    op.add_column('external_references', sa.Column('property_conversation_id', sa.Integer(), nullable=True))
    
    # Create new tables
    op.create_table('general_conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('is_logged_in', sa.Boolean(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_conversations_id'), 'general_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_general_conversations_session_id'), 'general_conversations', ['session_id'], unique=True)
    op.create_index(op.f('ix_general_conversations_user_id'), 'general_conversations', ['user_id'], unique=False)
    
    op.create_table('property_conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('property_id', sa.String(length=255), nullable=False),
        sa.Column('seller_id', sa.String(length=255), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.Column('property_context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_conversations_id'), 'property_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_property_conversations_session_id'), 'property_conversations', ['session_id'], unique=True)
    op.create_index(op.f('ix_property_conversations_user_id'), 'property_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_property_conversations_property_id'), 'property_conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_conversations_seller_id'), 'property_conversations', ['seller_id'], unique=False)
    
    op.create_table('general_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('intent', sa.String(length=50), nullable=True),
        sa.Column('message_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['general_conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_messages_id'), 'general_messages', ['id'], unique=False)
    op.create_index(op.f('ix_general_messages_conversation_id'), 'general_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_general_messages_timestamp'), 'general_messages', ['timestamp'], unique=False)
    
    op.create_table('property_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('intent', sa.String(length=50), nullable=True),
        sa.Column('message_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['property_conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_messages_id'), 'property_messages', ['id'], unique=False)
    op.create_index(op.f('ix_property_messages_conversation_id'), 'property_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_property_messages_timestamp'), 'property_messages', ['timestamp'], unique=False)
    
    # Add foreign key constraints to external_references
    op.create_index(op.f('ix_external_references_general_conversation_id'), 'external_references', ['general_conversation_id'], unique=False)
    op.create_index(op.f('ix_external_references_property_conversation_id'), 'external_references', ['property_conversation_id'], unique=False)
    op.create_foreign_key(None, 'external_references', 'general_conversations', ['general_conversation_id'], ['id'])
    op.create_foreign_key(None, 'external_references', 'property_conversations', ['property_conversation_id'], ['id'])
    # ### end Alembic commands ###
